#!/bin/bash

echo -e "Using Raspberry Pi OS\n"

# Update once
sudo apt update

# Install g++
if ! command -v g++ &> /dev/null
then
    echo "Installing g++"
    sudo apt install -y g++
else
    echo "g++ is already installed"
fi

# Install libbcm2835-dev
if dpkg -s libbcm2835-dev &> /dev/null
then
    echo "libbcm2835-dev is already installed"
else
    echo "Installing libbcm2835-dev"
    sudo apt install -y libbcm2835-dev
fi

echo -e "\nMake sure to use #include <bcm2835.h> in your C++ source file\n"

# Clone repo if it doesn't exist
if [ ! -d "./auto-room" ]; then
    echo "Cloning repository"
    git clone https://github.com/RainbowDesert57/auto-room.git
else
    echo "Repository already exists"
fi

# Ensure build directory exists
mkdir -p ./auto-room/build

echo -e "\nCompiling\n"
g++ ./auto-room/src/main.cpp -o ./auto-room/build/main -lbcm2835

